branches:
  - v[0-9]+.[0-9]+.[0-9]+
  - main
  - next
  - next-major
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/github'
    - - '@semantic-release/exec'
      - prepareCmd: 'echo "Preparing to release ${nextRelease.version}"'
        generateNotes: 'cz bump --files-only'

