# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

branches:
    - v[0-9]+.[0-9]+.[0-9]+
    - main
    - name: next
      prerelease: true

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - - '@semantic-release/git'
      - assets: ['CHANGELOG.md', 'package.json', 'package-lock.json']
        message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
    - '@semantic-release/github'
    - - '@semantic-release/exec'
      - prepareCmd: 'echo "Preparing to release ${nextRelease.version}"'
        generateNotes: 'cz bump --files-only'
