#!/usr/bin/env bash
# SPDX-FileCopyrightText: Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Install dependencies (internal)"
#MISE hide=true
pnpm install --config.confirmModulesPurge=false
