#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 - 2026 Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Clean build artifacts"
rm -rf dist/ coverage/ node_modules/.vite .rollup.cache guide/book
