#!/usr/bin/env bash
# SPDX-FileCopyrightText: Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Auto-fix formatting and linting issues"
#MISE depends=["_install"]
set -e
mise run prettier:fix
mise run eslint:fix
