#!/usr/bin/env bash
# SPDX-FileCopyrightText: Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Check code quality (format + lint + types)"
#MISE depends=["_install"]
set -e
mise run prettier:check
mise run eslint:check
pnpm exec tsc --noEmit
