#!/usr/bin/env bash
# SPDX-FileCopyrightText: Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Check code quality (format + lint + types)"
#MISE depends=["_install"]
mapfile -t CHANGED_FILES < <(git --no-pager diff --name-only --diff-filter=d --staged)
set -e
mise run prettier:check "${CHANGED_FILES[@]}"
mise run eslint:check "${CHANGED_FILES[@]}"
pnpm exec tsc --noEmit
