#!/usr/bin/env bash
# SPDX-FileCopyrightText: Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Lint with ESLint (no fixes)"
#MISE depends=["_install"]
set -e
pnpm exec eslint "$@"
