#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Lint with ESLint (auto-fix)"
#MISE depends=["_install"]
set -e
pnpm exec eslint --fix "$@"
