#!/usr/bin/env bash
# SPDX-FileCopyrightText: Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Run preflight checks for the website"
#MISE depends=["website:_install"]
#MISE dir="website"
pnpm exec astro check
