#!/usr/bin/env bash
# SPDX-FileCopyrightText: Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Run a live reloading dev environment"
#MISE depends=["website:_install"]
#MISE dir="website"
pnpm exec astro dev
