#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Check formatting with Prettier"
#MISE depends=["_install"]
set -e
pnpm exec prettier --check --ignore-unknown "$@"
