#!/usr/bin/env bash
# SPDX-FileCopyrightText: Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Check formatting with Prettier"
#MISE depends=["_install"]
set -e
pnpm exec prettier --check --ignore-unknown "$@"
