#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 - 2026 Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

#MISE description="Fix formatting with Prettier"
#MISE depends=["_install"]
set -e
pnpm exec prettier --write --ignore-unknown "$@"
